"""Regenerate RESULTS.md from ``studies/*.jsonl`` (never from a live engine)."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List

from hard_decisions.tasks import AXES, ROOT, Task, all_slugs


def _rows(path: Path) -> List[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _pct(x: float) -> str:
    return f"{100 * x:.1f}"


def _floor(value) -> str:
    return "-" if value is None else _pct(value)


def _cell(row: dict) -> str:
    return f"{_pct(row['accuracy'])} [{_pct(row['ci_low'])}-{_pct(row['ci_high'])}]"


def task_section(task: Task, studies: Path) -> List[str]:
    engines: Dict[str, List[dict]] = {}
    for path in sorted(studies.glob(f"{task.slug}-*.jsonl")):
        name = path.stem[len(task.slug) + 1:]
        if "-vs-" in name:
            continue
        engines[name] = _rows(path)
    lines = [f"## {task.slug}", ""]
    if not engines:
        return lines + ["No engine has been answered on this task yet.", ""]
    first = next(iter(engines.values()))
    overall = {e: next(r for r in rows if r["axis"] == "overall") for e, rows in engines.items()}
    lines += [f"Options: {', '.join(task.options)}. Accuracy is a percentage with a 95% bootstrap interval "
              f"in brackets. `best constant` is the accuracy of always giving the single most common answer "
              f"on the same items (`-` when a slice holds one gold label, where it is trivially 100%); `chance` is 1 divided by the number of options.", ""]
    lines += ["| engine | n | accuracy | macro-F1 | invalid | best constant | chance |", "|---|---|---|---|---|---|---|"]
    for e, r in overall.items():
        lines.append(f"| {e} | {r['n']} | {_cell(r)} | {r['macro_f1']:.3f} | {r['invalid']} | "
                     f"{_floor(r['best_constant'])} | {_pct(r['chance'])} |")
    lines.append("")
    recall_head = " | ".join(f"recall {o}" for o in task.options)
    lines += [f"| engine | {recall_head} |", "|---|" + "---|" * len(task.options)]
    for e, r in overall.items():
        lines.append(f"| {e} | " + " | ".join(
            "-" if r["recall"].get(o) is None else _pct(r["recall"][o]) for o in task.options) + " |")
    lines.append("")
    for axis, heading in AXES:
        values = [r["value"] for r in first if r["axis"] == axis]
        if not values or (len(values) == 1 and axis not in ("depth",)):
            continue
        lines += [f"### By {heading}", "", "| value | n | " + " | ".join(engines) + " | best constant |",
                  "|---|---|" + "---|" * (len(engines) + 1)]
        for value in values:
            cells, n, floor = [], 0, None
            for e, rows in engines.items():
                match = next((r for r in rows if r["axis"] == axis and r["value"] == value), None)
                cells.append(_cell(match) if match else "-")
                if match:
                    n, floor = match["n"], match["best_constant"]
            lines.append(f"| {value} | {n} | " + " | ".join(cells) + f" | {_floor(floor)} |")
        lines.append("")
    pairs = sorted(p for p in studies.glob(f"{task.slug}-*-vs-*.jsonl"))
    if pairs:
        lines += ["### Paired differences (same items; accuracy difference in points)", "",
                  "| comparison | slice | n | difference | 95% interval |", "|---|---|---|---|---|"]
        for path in pairs:
            for r in _rows(path):
                lines.append(f"| {r['engine_a']} minus {r['engine_b']} | {r['axis']}={r['value']} | {r['n']} | "
                             f"{100 * r['diff']:+.1f} | {100 * r['ci_low']:+.1f} to {100 * r['ci_high']:+.1f} |")
        lines.append("")
    return lines


def render(*, root: Path = ROOT) -> str:
    lines = ["# Results", "",
             "Generated by `hd report` from `studies/*.jsonl`; do not edit by hand. Each task is a sample "
             "of the ProofWriter test set built by `hd build` (see `tasks/*/build.json` for its parameters "
             "and strata).", ""]
    for slug in all_slugs(root):
        lines += task_section(Task.load(slug, root=root), Path(root) / "studies")
    return "\n".join(lines).rstrip() + "\n"


def write(*, root: Path = ROOT) -> Path:
    path = Path(root) / "RESULTS.md"
    path.write_text(render(root=root), encoding="utf-8")
    return path
